# Generated by Django 6.0.5 on 2026-05-17 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Opera (es. Dune: Parte Due)')),
                ('release_year', models.IntegerField(verbose_name='Anno di uscita')),
                ('media_type', models.CharField(choices=[('film', 'Film'), ('serie', 'Serie TV'), ('storie', 'Storie'), ('racconti', 'Racconti'), ('audiolibri', 'Audiolibri')], max_length=20, verbose_name='Tipo di Media')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Immagine di Copertina')),
                ('team_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Voto Redazione')),
                ('short_description', models.TextField(max_length=300, verbose_name='Estratto/Sinossi breve')),
                ('content', models.TextField(verbose_name="Testo Completo dell'Articolo")),
                ('audio_track', models.FileField(blank=True, null=True, upload_to='audio_fragments/', verbose_name='Traccia Audio (Opzionale)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Link Video (Opzionale)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='In Evidenza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autore (Team)')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='core.category')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-created_at'],
            },
        ),
    ]
