# Generated by Django 6.0.5 on 2026-05-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Traccia/Capitolo')),
                ('audio_file', models.FileField(upload_to='audiobooks/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine (1, 2, 3...)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chapters', to='core.article')),
            ],
            options={
                'verbose_name': 'Traccia Audio',
                'verbose_name_plural': 'Tracce Audio',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Lascia vuoto se è un racconto unico', max_length=200, verbose_name='Titolo Capitolo')),
                ('content', models.TextField(verbose_name='Testo del Capitolo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine (1, 2, 3...)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_parts', to='core.article')),
            ],
            options={
                'verbose_name': 'Capitolo Racconto',
                'verbose_name_plural': 'Capitoli Racconto',
                'ordering': ['order'],
            },
        ),
    ]
