# Generated by Django 6.0.5 on 2026-05-19 20:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiochapter_storypart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_track',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audio_fragments/', verbose_name='Traccia Audio (Opzionale)'),
        ),
        migrations.AlterField(
            model_name='audiochapter',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audiobooks/'),
        ),
    ]
